README.md

I had a look at the code and noticed the mismatch

Changed buildCommand to buildMethod

---

.github/workflows/main.yml
README.md
action/steps/build.sh

Relates to webbertakken/unity-builder#19

Separate custom params

---

.github/workflows/main.yml
README.md

The emoji in the github action name exposed as a env variable through docker was causing a gradle crash 😢.
This PR depends on #105, DO NOT MERGE until after #105 is landed.

Add support for android builds

---

.github/workflows/cleanup.yml

- This will remove artifacts older than 21 days to prevent enormous data usage (100GB+) for no reason

remove artifacts older than 21 days

---

action/steps/build.sh

Added -nographics flag to build.sh

---

action/steps/activate.sh
action/steps/build.sh
action/steps/return_license.sh

- This will solve #172 where both the dockerfile and the github action were adding -batchmode flag.

Remove duplicate flag batch-mode

---

src/model/image-tag.js

- Convert version major and minor to numbers

Convert version major and minor to numbers

---

.github/workflows/main.yml

- This updates packages that caused workflows to fail due to use of deprecated features in setup node.

update deprecated workflow

---

.github/workflows/activation.yml
.github/workflows/cleanup.yml
.github/workflows/main.yml

- This adds a request for the activation file on demand.

add activation workflow and set retention periods

---

.github/workflows/main.yml

- Use `pull_request_target` to run pull request workflow on the workflow of `main` to be able to use secrets.
- Move license to secrets
- Reduce exposure of ENV variables that hold secrets
- Checkout the code from the PR to run the test builds against
- Ignore changes in github workflows as it can become rather confusing if you try to change a workflow, when it doesn't trigger on the PR itself, but on main only.

Secure licenses

---

.github/ISSUE_TEMPLATE/config.yml

- Adds discord link in issues screen

Add Discord link in issues

---

dist/default-build-script/Assets/Editor/UnityBuilderAction/Versioning/Git.cs

- Add namespace to avoid name conflict

Closes #243

---

dist/steps/build.sh
src/model/versioning.ts

- Cleanup build.sh
- Fixes https://github.com/game-ci/unity-builder/issues/258
- Quickly add an extra line to dirty branch explaining which untracked changes have been found since checkout.

Ensure proper read permissions and cleanup build.sh

---

.github/ISSUE_TEMPLATE/feature_request.md

add default tag for feature request

---

src/model/unity-versioning.test.ts
src/model/unity-versioning.ts

- Improve error message when unity version settings file is not found.

Projectpath error message

---

dist/entrypoint.sh
dist/steps/activate.sh
dist/steps/return_license.sh

- Port original fix from https://github.com/game-ci/unity-test-runner/pull/109/files

Run license activation in an empty directory

---

.github/ISSUE_TEMPLATE/feature_request.md
action.yml
dist/steps/set_gitcredential.sh
src/model/__mocks__/input.ts
src/model/build-parameters.ts
src/model/docker.ts
src/model/input.ts
src/model/unity-versioning.test.ts
src/model/unity-versioning.ts
yarn.lock

- Add gitPrivateToken changes by @mad01

Add gitPrivateToken

---

dist/default-build-script/Assets/Editor/UnityBuilderAction/Versioning/VersionApplicator.cs
src/model/android-versioning.test.ts
src/model/android-versioning.ts

- Increase limit per https://github.com/game-ci/documentation/pull/222#issuecomment-936099761
- Don't apply androidVersionCode if Versioning strategy is set to none.

Improve androidVersionCode parsing and application

---

dist/steps/activate.sh

Fix docs link

---

.github/workflows/versioning.yml

- Remove deprecated param from versioning

Remove deprecated param from versioning

---

.github/workflows/mac-build-tests.yml

Fix minor typo in mac build test workflow

---

dist/xhr-sync-worker.js
src/model/image-environment-factory.ts

- Closes https://github.com/game-ci/unity-builder/issues/334

Fix Android build parameters error

---

src/model/image-environment-factory.ts

- Fix for https://github.com/game-ci/unity-builder/issues/345

Fix license issue

---

src/model/image-environment-factory.ts

- androidTargetSdkVersion no longer worked because androidSdkManagerParameters was dropped, so restoring it

Restore androidSdkManagerParameters

---

.github/workflows/cloud-runner-aws-pipeline.yml
.github/workflows/cloud-runner-k8s-pipeline.yml
src/model/cli/remote-client/setup-cloud-runner-repository.ts
src/model/cloud-runner/steps/setup-step.ts

Minor cleanup and simplification of Cloud Runner pipelines.
Includes simple fix to target correct cloud runner branch and target repo branch.

Minor tweaks and corrections for cloud runner pipeline and branch parameter

---

src/model/image-tag.ts

Fix mac builds

---

dist/platforms/mac/steps/return_license.sh

- Fixes https://github.com/game-ci/unity-builder/issues/358

Fix mac return license

---

src/model/image-environment-factory.ts

- Fixes https://github.com/game-ci/unity-builder/issues/409

Fix ANDROID_TARGET_SDK_VERSION environment variable is missing

---

.github/workflows/cats.yml

- This updates the action cats, so that the pictures are properly shown

chore: update action-cats

---

lefthook.yml

- Remove the audit check on pre-push

chore: remove audit pre push

---

dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs

- Fix for newer versions of Android API levels that do not get correctly parsed.

Fix androidTargetSdkVersion

---

.github/FUNDING.yml

Add sponsor button that allows users to natively support us through GitHub

chore: add game-ci github sponsoring option

---

src/model/cloud-runner/remote-client/index.ts
src/model/cloud-runner/services/cloud-runner-custom-steps.ts

- Fix: retained workspaces must fetch before resetting to needed commit
- Fix: expect large packages inside {project}/Packages/ rather than {project} root
- Preview feature: deploy to steam from cloud runner environment
- [x ] Readme (updated or not needed)
- [x ] Tests (added, updated or not needed)

Fix: retained workspaces must fetch before resetting to needed commit

---

src/model/docker.ts
src/model/image-environment-factory.ts

- Remove GITHUB_WORKSPACE from image-environment-factory.ts
- Fix windows workdir path in docker run command

fix: Misc minor issues in image-environment-factory and windows docker

---

src/model/platform-setup/setup-mac.ts

- Installs Unity modules based on target platform (macos, ios, android)

feat(mac): Install mac Unity modules based on target platform for greater flexibility

---

.github/workflows/cloud-runner-async-checks.yml

Enable workflow dispatch (for checks workflow) by adding simple workflow to main

---

README.md

Fix Builds Status Badge

---

dist/platforms/mac/steps/build.sh
src/model/platform-setup/setup-mac.ts

- Making `manualExit` option work on mac machines.
Tested on private self-hosted runner, cannot share here.

Fixed manualExit option on Mac machines

---

.github/workflows/build-tests-mac.yml
.github/workflows/build-tests-ubuntu.yml
.github/workflows/build-tests-windows.yml
test-project/ProjectSettings/ProjectSettingsIl2cpp.asset

- Fix test workflow issues found in 4.2.0 hotfixes
- Add additional tests to catch issues found in 4.2.0 hotfixes

Fix test workflows
