game-ci/unity-builder

.github/workflows/main.yml, src/model/docker.js
Not sure if anything else needs to be updated, but this should solve my Issue at webbertakken/unity-actions#26.
I set `UNITY_EMAIL`, `UNITY_PASSWORD`, and `UNITY_SERIAL` in my fork so that the test builds would pass, but my Plus license is limited to only 2 activations at a time, so the remaining builds may still fail...
=> docker.js now sets variables for Pro licenses as well

builder/steps/return_license.sh
If $UNITY_SERIAL isn't defined then the license return step gets skipped to help save some time in personal builds.
=> Only return the license in professional mode

builder/steps/activate.sh
Adds more checks for professional license details before running a build.
This should stop builds running without a licenses setup and will exit with a more explicit error
Edit: also removed the exit from the professional activation since that was being called even when activation was successful
=> feat(activate): add more checks for licenses

action/steps/build.sh
Potential fix for: https://github.com/webbertakken/unity-builder/issues/77
Questions:
- The contributor guidelines request adding tests, but given that this happens in the shell script I wasn't certain if/how to do that best. Any suggestions, or is a manual verification good enough?
- In the issue it discusses fixing Linux builds as well, but I haven't yet tested if they're broken or determined the path where the executable would need to be updated. Do we want to include that here as well or just Mac?
=> make StandaloneOSX app runnable

action.yml
This helps avoid warnings when using previously undocumented inputs
=> Document additional action inputs

.github/workflows/main.yml
Removing androidVersionCode from the workflow of this repo to make sure the automatic versioning stays in tact
=> Remove androidVersionCode from workflow

action/default-build-script/Assets/Editor/Builder.cs, action/steps/build.sh
`-version` is now used (as of 2019.4.8f1 or earlier) by the Unity CLI to print its own version, then exit with code 0. This interferes with `unity-builder`'s version passing, so I propose renaming the argument to something less likely to collide.
I was unable to run Yarn as requested in the contributing guidelines, as I'm missing tons of prerequisites. Besides whatever CI checks this repo can provide, I can confirm that this fixed #136 in my game's workflow.
=> Rename custom -version flag to -buildVersion

action/entrypoint.sh
This adds a self-help message
It is meant to prevent getting messages like this on discord and in issues multiple times a week:
> Hi i have error
> ```
> Unity exited with code XX
> ```
> I think it's a bug because i did everything correctly.
=> Add intructions for debugging

action/steps/build.sh
**Changes**
Small change in build script to fix android build signing using androidKeystoreBase64. The problem is observed when the unity project isn't located in the root of the repository. 
Let say you encoded keystore to base64 and it is already in github secrets. Configuration for builder will have these lines:
```
androidKeystoreName: my2.keystore
androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64}}
```
So during the build base64 will be decoded to `repo/my2.keystore`. 
```
echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$ANDROID_KEYSTORE_NAME"
```
And the value androidKeystoreName will be passed to unity build script
```
if (options.TryGetValue("androidKeystoreName", out string keystoreName) && !string.IsNullOrEmpty(keystoreName))
PlayerSettings.Android.keystoreName = …
```
=> Decode keystore to project folder

action/default-build-script/Assets/Editor/Builder.cs
- In unity there is an options to add https://docs.unity3d.com/ScriptReference/BuildOptions.html into build. This change allow user to add customParameters as normal (-EnableHeadlessMode) and if any of these are in that Enum they will be taken into account for the build.
=> Pass buildOptions to the build with customParameters

src/model/versioning.js
Would like to remove this debug option, as I don't like how it generates many unnecessary warnings, and I don't think it provides any value.
- Remove these:
=> Remove debug from versioning

README.md, package.json
- Update repo url from webbertakken to game-ci inside package.json
- Change status badges to also refer to game-ci
=> Update repo url and status badges

src/model/docker.ts
To automatically upload symbols to unity, we need to define the `USYM_UPLOAD_AUTH_TOKEN` variable. Currently the build container ignores this variable, even if it's defined in the github action.
```
2021-03-26T02:35:35.5938747Z time="2021-03-26T02:35:35Z" level=fatal msg="Please provide an auth token with USYM_UPLOAD_AUTH_TOKEN environment variable"
```
- Passes on `USYM_UPLOAD_AUTH_TOKEN` to the docker process, if it's defined
=> Pass on USYM_UPLOAD_AUTH_TOKEN if defined

dist/default-build-script/Assets/Editor/UnityBuilderAction/Builder.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/UnityBuilderAction.asmdef
- Use reflection instead of version defines to see if the addressables package is installed.
Fixes #233
=> Fix build script for Unity 2018, by using reflection instead of version defines

action.yml, dist/steps/build.sh, src/model/__mocks__/input.ts, src/model/aws.ts, src/model/build-parameters.ts, src/model/docker.ts, src/model/input.ts, src/model/kubernetes.ts
Fixes #219, without causing the issues caused by #141 
- Adds a `chownFilesTo` input
- `chown`s the files to whatever the input string is
Use it like this:
```Dockerfile
- uses: Bradshaw/unity-builder@main
env:
UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
with:
unityVersion: ${{ matrix.unityVersion }}
targetPlatform: ${{ matrix.targetPlatform }}
chownFilesTo: "1000:1000"
```
And it does this after building:
```sh
if [[ -n "$CHOWN_FILES_TO" ]]; then
if [[ -n "$BUILD_PATH_FULL" ]]; then
chown -R $CHOWN_FILES_TO $BUILD_PATH_FULL
fi
if [[ -n "$UNITY_PROJECT_PATH" ]]; then
chown -R $CHOWN_FILES_TO $UNITY_PROJECT_PATH
fi
if [[ -n "$CUSTOM_BUILD_PATH" ]]; then
chown -R …
```
=> Chown files to a custom user after building (fix file ownership)

dist/default-build-script/Assets/Editor/UnityBuilderAction/Builder.cs
- Edited reflection GetMethod for BuildPlayerContent to solve AmbiguousMatchException for addressables. (https://discord.com/channels/710946343828455455/710946344264794219/843855407402319893)
-  Addressable version 1.17.17+ introduced new BuildPlayerContent method and the old CallAddressablesMethod("BuildPlayerContent", Array.Empty<object>()); throws AmbiguousMatchException when building the addressables. (https://docs.unity3d.com/Packages/com.unity.addressables@1.17/manual/BuildPlayerContent.html)
=> Fixed addressable build failing on Addressable 1.17.17+

dist/Dockerfile, dist/steps/activate.sh, dist/steps/build.sh, dist/steps/return_license.sh
- Remove -nographics flag
- Ensure -batchmode flag is set (only once) (currently is set in the docker [alias `unity-editor`](https://github.com/game-ci/docker/blob/5269da7520bdb336606ff8bbc44dc6983f7a1889/editor/Dockerfile#L39)) 
- Install libnotify (to be moved to the docker repo).
- Set debian frontend to default `Noninteractive`.
- I tried the solutions from https://unix.stackexchange.com/questions/2881/show-a-notification-across-all-running-x-displays, specifically the ones that seemed to make it possible to output events in tty console. However this doesn't seem to work in `Noninteractive` mode. 
- Many options require xserver to even listen to dbus.
- Relies on: https://github.com/game-ci/docker/pull/115
(which means the fix will only fully work after docker images v0.13 release)
- …
=> Remove -nographics flag, ensure single -batchmode flag

action.yml, dist/Dockerfile, src/index.ts, src/model/__mocks__/input.ts, src/model/action.ts, src/model/build-parameters.ts, src/model/docker.ts, src/model/input.ts
- This PR is a proposal to fix this issue: https://github.com/game-ci/unity-builder/issues/161
- In order to get the SSH_AUTH_SOCK we used https://github.com/webfactory/ssh-agent/issues/11
- sshAgent is an optional input parameter.
```
- name: Setup SSH Agent
uses: webfactory/ssh-agent@v0.5.2
with:
ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
- name: Unity Builder
uses: ivan-hernandez-scopely/unity-builder@feature/ssh-agent-for-private-upm
env:
UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
with:
projectPath: ${{ matrix.projectPath }}
targetPlatform: ${{ matrix.targetPlatform }}
sshAgent: ${{ env.SSH_AUTH_SOCK }}
```
=> Using SSH_AUTH_SOCK (ssh agent forwarding) to pull upm private repos

action.yml, dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs, dist/entrypoint.sh, dist/steps/build.sh, dist/steps/set_gitcredential.sh, src/model/__mocks__/input.ts, src/model/android-versioning.test.ts, src/model/android-versioning.ts, src/model/build-parameters.test.ts, src/model/build-parameters.ts, src/model/docker.ts, src/model/input.test.ts, src/model/input.ts
- Add androidTargetSdkVersion as an option to update the Android SDK
=> Add androidTargetSdkVersion as an option to update the Android SDK

action.yml, dist/xhr-sync-worker.js, src/model/input.ts
- Moved targetPlatform and customParameters up to match order in docs
- Moved cloud runner params down
=> Sync docs2

dist/platforms/ubuntu/entrypoint.sh
This PR supersedes https://github.com/game-ci/unity-builder/pull/308 which has been inactive for a while. I've kept the author of the commit in tact.
---
if there is both a unity package and a test-project in one github repo, then the token generation process is created Library folder and then the build of the test project breaks. Requires a tilde to ignore Library folder in _activate-license.
Or need set the path ACTIVATE_LICENSE_PATH from the global ENV in runtime-action
- ...
=> Update licensing path, to be treated as temporary/invisible path

src/model/docker.ts
When using a self-hosted runner with SELinux (fedora)
volumes need to be mounted with ":z" in order to have write access
these flags are documented [here](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label)
Also the in self-hosted runners, _temp is empty, so this creates the child folders.
- mount volumes with SELinux labels
- create folders _github_home and _github_workflow if they are missing
=> feat: compatibility with self-hosted runners with SELinux

src/model/docker.ts
Running docker currently mounts the docker.sock file into the container.
This was introduced in 2ab738c08389696888fa13b09fb29d02932a00b3 but
there is no explanation provided.
The docker.sock file is only needed if we want to run docker inside the container
to create other images or start other containers.
I searched through the code and I did not find any such use.
In particular, on fedora this gives permission denied because docker.sock
is owned by root and the container runs under an unprivileged user.
One has to change the permissions of docker.sock
(which is actually a link to /run/podman/podman.sock) to be writeable by the user.
If we don't need to use docker inside the containers,  then we can remove this file,
thus we can run this GitHub action as an unprivileged user out of the …
=> feat: work with rootless docker

.gitattributes, .gitignore
- Changes attributes to force `lf` line-endings for generated files. Enable text-diff (`text`), but disable showing them in PR diff (`-diff linguist-generated=true`)
- Add attribute for binary (`-text -diff`)
- Add `.orig` file exclusion for git, since on MacOS, lefthook seems to create .orig files.
=> fix: ensure line endings

dist/platforms/ubuntu/steps/set_gitcredential.sh, src/model/docker.ts
#310 accidentally removed support for `gitPrivateToken`
This PR should fix this again.
Also transitive `ssh://git@github.com` url substition did not work for me which is the reason for the change in `dist/platforms/ubuntu/steps/set_gitcredential.sh`
=> Add gitPrivateToken support again

dist/platforms/mac/steps/build.sh
Fixes error described here: https://forum.unity.com/threads/ios-build-is-failing-seems-like-a-fastlane-problem-not-sure-how-to-proceed.682201/
- Add username and password to mac build.sh
=> Fix iOS Fastlane build when using Unity Cloud Diagnostics

dist/platforms/mac/steps/build.sh
- As a workaround for an error in Mac builds on 2021.3, first write logs to file, and then display the logs afterwards: https://forum.unity.com/threads/exception-occurred-inside-beedriver.1139905/
=> Fix for 2021.3 Mac builds

dist/platforms/ubuntu/steps/set_gitcredential.sh
when using `gitprivatetoken`, the build logs showed an error
``` 
warning: ***github.com/.insteadof has multiple values
error: cannot overwrite multiple values with a single value
Use a regexp, --add or --replace-all to change ***github.com/.insteadOf. 
```
substitution url for https did not work.
this fix would add a value for https instead of overwriting it
=> fix: git private token not being set correctly for https

dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs
- If a user does not set `useCustomKeystore` in their project settings, the keystore information that they input into `unity-builder` gets ignored by Unity. Therefore, we should enforce `useCustomKeystore = true` if the user inputs keystore info.
=> Fix missing Android custom keystore

dist/platforms/windows/build.ps1
https://github.com/game-ci/unity-builder/issues/434 will show that no Windows builds are currently capable of sending `androidVersionCode` or any other Android parameters. This can be fixed very simply by adjusting the build script to pass these parameters. Compare the following two files:
- https://github.com/game-ci/unity-builder/blob/cdee7d1d9a8ab9eccc408a37832b43d6afa73507/dist/platforms/windows/build.ps1#L112
- https://github.com/game-ci/unity-builder/blob/cdee7d1d9a8ab9eccc408a37832b43d6afa73507/dist/platforms/ubuntu/steps/build.sh#L138
It's clear that the current Windows build script is omitting certain parameters. This will resolve that issue (linked in commit message header).
```diff
diff --git a/dist/platforms/windows/build.ps1 b/dist/platforms/windows/build.ps1
index …
```
=> Pass Android parameters for Windows builds, fixes #434

dist/licenses.txt, package.json, yarn.lock
The current version of actions/core produces a lot of warning about deprecated set-output command,  like this:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
the new version of actions/core uses the environment files instead, so this version bump should fix the warning
- ...
=> update actions core to 1.10.0

action.yml
node12 actions are deprecated.
See documentation here:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Currently, the unity builder action gives me the following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: game-ci/unity-test-runner, game-ci/unity-builder
```
- ...
=> upgrade to node 16

dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs
Discovered when the gameci/docker repo CI failed in [this PR](https://github.com/game-ci/docker/pull/188).
> Assets/Editor/Editor/UnityBuilderAction/Input/AndroidSettings.cs(14,32): error CS0117: 'PlayerSettings.Android' does not contain a definition for 'useCustomKeystore'
It's complaining about the line added in this [unity-builder commit](https://github.com/game-ci/unity-builder/commit/36891ec921c5f3163ea1ca6c12496c02abdaaf51) on May 21st.
```
PlayerSettings.Android.useCustomKeystore = true;
```
[useCustomKeystore](https://docs.unity3d.com/2019.3/Documentation/ScriptReference/PlayerSettings.Android-useCustomKeystore.html) was added in Unity 2019 which is why 2018 builds fail.
Might also be worth adding Unity 2018 to the [CI version …
=> Fix: builds for Unity versions less than 2019 fail

dist/platforms/windows/build.ps1
Powershell inserts double-quotes around the entire $Env:CUSTOM_PARAMETERS variable when it's added to the unity command line.  This causes simple command line parsers (like the one you provide as an example) to fail, because it treats the entire custom parameters string as a single argument.
This likely affects powershell only (not bash).  This PR includes a trick to parse the CUSTOM_PARAMETERS into an array, while still respecting any individual custom parameters values that may be quoted.
Here's a simple powershell script that illustrates the problem and solution:
```powershell
$Env:CUSTOM_PARAMETERS = '-customParams1 "custom value 1" -customParam2 custom_value_2'
& cmd.exe /C echo `
-buildTarget `
StandaloneWindows64 `
$Env:CUSTOM_PARAMETERS `
-logFile
#
#
$_, $customParamsArray = …
```
=> Fix powershell quotation issue, when CUSTOM_PARAMETERS contains spaces

action.yml, dist/platforms/ubuntu/steps/build.sh, dist/platforms/windows/build.ps1, src/index.ts, src/model/output.test.ts, src/model/output.ts, src/model/platform-setup.ts, src/model/platform-setup/index.ts, src/model/platform-setup/setup-android.ts
- Create android keystore on windows when available
- Output android version code
Needs https://github.com/game-ci/documentation/pull/349
=> feat: Android updates for Windows and androidVersionCode output

action.yml
- Add default value for androidExportType
=> Add default value for androidExportType

action.yml, src/model/input.ts
=> Fix defaults

dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs
- Fix reflection code for setting buildAppBundle
- Mark AndroidSettings class as static
=> Fix reflection code for setting buildAppBundle

action.yml
- Revert androidSymbolType to none
As requested in game-ci/documentation#363
=> Revert android symbol to none

dist/default-build-script/Assets/Editor/UnityBuilderAction/Builder.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/ArgumentsParser.cs
- Added support for -standaloneBuildSubtarget parameter via customParameters in order to facilitate dedicated server builds. Since Unity introduced the subtarget option in 2021.2, this parameter only takes effect in supported Unity versions.
Documentation PR: https://github.com/game-ci/documentation/pull/389
Discussion: https://github.com/game-ci/documentation/issues/240
=> Build subtarget support for Unity 2021.2+

src/model/platform-setup/setup-mac.ts
- Fix a bug that existsSync(this.unityHubExecPath) always returns false
=> Fix macOS unity base path so that unity existence check works as intended

.github/workflows/build-tests-mac.yml, .github/workflows/build-tests-ubuntu.yml, .github/workflows/build-tests-windows.yml
Changed referenced EOL versions in tests to LTS and Current versions (2018.x-2020.x -> 2021.x-2023.x)
=> Removed checks for old unity versions

action.yml, dist/platforms/ubuntu/steps/build.sh, src/model/build-parameters.ts, src/model/image-environment-factory.ts, src/model/input.test.ts, src/model/input.ts
- Adds `with: manualExit` parameter to the action, that when present suppresses the Unity `-quit` command line argument. See https://github.com/game-ci/cli/issues/13 and https://github.com/game-ci/unity-builder/issues/442
=> `manualExit` suppresses `-quit`, useful for buildMethods with async calls

dist/platforms/ubuntu/steps/build.sh
Fix #581:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
at com.***.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
at com.***.repository.api.SchemaModule.<init>(SchemaModule.java:75)
at com.***.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
at com.***.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
at com.***.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at …
```
=> fix android sdkmanager invocation

.github/pull_request_template.md, .github/workflows/activation.yml, .github/workflows/build-tests-mac.yml, .github/workflows/build-tests-ubuntu.yml, .github/workflows/build-tests-windows.yml, .github/workflows/cleanup.yml, .github/workflows/cloud-runner-ci-pipeline.yml, .github/workflows/integrity-check.yml, dist/platforms/windows/activate.ps1, dist/platforms/windows/build.ps1, dist/platforms/windows/entrypoint.ps1, dist/platforms/windows/return_license.ps1, src/model/image-tag.test.ts, src/model/image-tag.ts
- Fix Unity Pathing
- Update tests to use windows-2022 for new images
- Bump docker image tag
- Bump action versions
- Improve PR template
- Fix workflow naming for Macos
- Only build test project on supported Unity versions (LTS and latest tech stream)
Note: Tests will fail while images don't exist. The docker repo tests contain a representative test run of these changes [here](https://github.com/game-ci/docker/actions/runs/6682517570/job/18169031828).
=> Additional Windows Image Updates

action.yml, dist/platforms/mac/entrypoint.sh, dist/platforms/windows/build.ps1, dist/platforms/windows/entrypoint.ps1, src/model/build-parameters.ts, src/model/docker.ts, src/model/exec-with-error-check.ts, src/model/image-tag.test.ts, src/model/image-tag.ts, src/model/input.ts, src/model/platform-setup/setup-mac.ts
- Windows now exits with the proper exit codes. This mirrors Ubuntu behavior properly now and means we do not need the error parsing logic to handle error conditions which means we should be back to v2 behavior.
- Allow customizing image registry/image version
- Only create the licensing directory on Mac if it doesn't already exist. Don't delete the folder on build complete. This means builds nominally shouldn't need sudo permissions, very useful for self-hosted runners.
- Pick correct architecture when installing macos editor to support both x86 and arm-based systems
- https://github.com/game-ci/unity-builder/issues/564
- https://github.com/game-ci/unity-builder/issues/563
- https://github.com/game-ci/unity-builder/issues/578
- https://github.com/game-ci/unity-builder/issues/572
- …
=> Additional Fixes and Improvements

dist/platforms/ubuntu/entrypoint.sh
- chmod blank project folder to fix host permission errors
- https://github.com/game-ci/unity-builder/issues/598
=> Ensure blank project files can be deleted by github runner

action.yml, dist/platforms/mac/steps/build.sh, src/model/build-parameters.ts, src/model/image-environment-factory.ts, src/model/input.test.ts, src/model/input.ts, src/model/platform-setup/setup-mac.ts
- Similarly to `-manualExit` allows to disable `-nographics` for macOS build invocation
- Purpose of this is to run the builder on gpu-enabled machines that use GPU during build process
- [manualExit suppresses -quit, useful for buildMethods with async calls](https://github.com/game-ci/unity-builder/pull/574)
Validated inside org repository.
=> Add 'enableGpu' param, allowing running Unity w/o `-nographics`

src/model/unity-versioning.test.ts, src/model/unity-versioning.ts
- Support new Unity versioning scheme (https://forum.unity.com/threads/unity-6-new-naming-convention.1558592/)
=> Use capture group to find Unity version to support new 6000 versions

src/model/image-tag.test.ts, src/model/image-tag.ts
- Update version checking in image-tag.ts to support 6000+ Unity versions.
=> Hotfix: Fix version checking in image-tag

dist/platforms/windows/activate.ps1, dist/platforms/windows/return_license.ps1, src/model/docker.ts, src/model/platform-validation/validate-windows.ts
Hello
A simple version of unity licensing server support for Windows using the same logic as the existing Linux implementation. 
- Modify the step files `activate.ps1` and `return_license.ps1` to replicate what is done in `activate.sh` and `return_license.sh`
- Update `validate-windows.ts` to allow this option to pass through for a Windows build
- Update `docker.ts` to correctly copy the unity config file necessary for unity licensing server request
- [468](https://github.com/game-ci/unity-builder/pull/468) : the Linux implementation of this feature
=> Enable unity licensing server for Windows

dist/platforms/windows/set_gitcredential.ps1
- Windows: fixed an error in `set_gitcredential.ps1` where `url.` was inside of the string, resulting in errors when building `with: gitPrivateToken` 
- I think right now there is none 
- I think right now there is none 
- This only affects private repos. Cannot share a workflow run here unfortunately.
- Comparing the changes to [linux](https://github.com/game-ci/unity-builder/blob/main/dist/platforms/ubuntu/steps/set_gitcredential.sh) might suffice.
=> fix(windows): replacing of urls if gitPrivateToken is set

dist/default-build-script/Assets/Editor/UnityBuilderAction/Builder.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/AndroidSettings.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Input/ArgumentsParser.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Reporting/CompileListener.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Reporting/StdOutReporter.cs, dist/default-build-script/Assets/Editor/UnityBuilderAction/Versioning/Git.cs
Removed all instances of interpolated strings from editor scripts so we don't get compiler errors on old versions of .NET in Unity 2018
- ...
- ...
- ...
PRs don't have access to secrets so you will need to provide a link to a successful run of the workflows from your own
repo.
- ...
- [Not needed] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make a PR
- [Not needed] Readme (updated or not needed)
- [Not needed] Tests (added, updated or not needed)
=> Unity 2018 and .NET 3.5 support
